### PR TITLE
Changes to facilitate CMake builds.

### PR DESCRIPTION
**Pull request by Net5F**
These changes facilitate building this project as a static library through CMake.

Due to files moving, the original build scripts would have to be fixed.

### CODE REVIEW

**Comment by anderspitman** [comment]
lol @Mmpuskas what's going on in here?

**Comment by Net5F** [comment]
@anderspitman A year later, I'm recovered from my previous efforts enough to start working on an mmo again XD

The concept has been paired down to being a long-term open-source social mmo project. Kinda stardew valley + neopets + second life, just a world with fun things to do with other people. The repo hasn't been cleaned up yet since I'm still working on the base infrastructure, but here it is. [https://github.com/Mmpuskas/Amalgam](https://github.com/Mmpuskas/Amalgam) 

The eventual work is set up in a very modular way so that I (or anyone else) can bite off individual features over time and feel like progress was made. Currently getting the big chunk of basic infrastructure done so that the modular development can start. [https://trello.com/b/dT78SOr4/amalgam-feature-roadmap](https://trello.com/b/dT78SOr4/amalgam-feature-roadmap)

I have a friend that's interested in contributing and eventually using the engine for a single-player game, so I'm thinking it will be a general 2D engine with built-in support for networking at any scale. I decided to do this instead of using an existing engine because of the lack of a good engine that only does 2d and uses an ECS that's compatible with efficient networking. After my time in unreal, I don't want to keep dealing with 3d physics, maps, and editors for long-term 2d projects.

Forgot this PR was up. I'm gonna close it and keep working off the fork.

**Comment by anderspitman** [comment]
@Mmpuskas nice! Do you guys have a discord or anything set up? Would be fun to catch up. My friends staged a coupe and bailed on Matrix for FB messenger so I haven't been on Matrix in forever.

**Comment by Net5F** [comment]
@anderspitman My discord is ArchdukeChocula#6136, shoot me a message!

**Pull request closed without merging**
